#!/bin/bash

# Variables
RPCPORTS="49152-49172"

DOMAIN_FQDN_LCASE=${DOMAIN_FQDN,,}
DOMAIN_FQDN_UCASE=${DOMAIN_FQDN^^}
DOMAIN_NETBIOS=${DOMAIN_FQDN_UCASE%%.*}

CONFIG_DIR=/etc/samba/config
CONFIG_FILE=$CONFIG_DIR/smb.conf

PROVISION_SCRIPT=samba-provision.sh
